--Aaron Michael Kurth
--Project 2 

spool F:\Documents\School\INSY3304\Project2_amk.txt

set echo on

--drop tables
DROP TABLE APPTDETAIL_amk;
DROP TABLE APPOINTMENT_amk;
DROP TABLE REASON_amk;
DROP TABLE STATUS_amk;
DROP TABLE BLOCK_amk;
DROP TABLE PATIENT_amk;
DROP TABLE DOCTOR_amk;
DROP TABLE BILLINGTYPE_amk;
DROP TABLE INSCO_amk;

--Part Ia. Create Tables

CREATE TABLE INSCO_amk (
InsCoID		NUMBER(3,0),
InsCoName	VARCHAR(20),
PRIMARY KEY (InsCoID)
);

CREATE TABLE BILLINGTYPE_amk (
Billingtype		VARCHAR(2),
BillingTypeDesc	VARCHAR(20)	NOT NULL,
PRIMARY KEY (BillingType)
);

CREATE TABLE DOCTOR_amk (
DoctorID		NUMBER(1,0),
DoctorFName	VARCHAR(20)	NOT NULL,
DoctorLName	VARCHAR(20)	NOT NULL,
PRIMARY KEY (DoctorID)
);

CREATE TABLE PATIENT_amk (
PatientID		NUMBER(3,0),
PatientFName	VARCHAR(20)	NOT NULL,
PatientLName	VARCHAR(20)	NOT NULL,
PatientPhone	VARCHAR(10),
PRIMARY KEY (PatientID)
);

CREATE TABLE BLOCK_amk (
BlockCode	CHAR(2),
BlockDesc	VARCHAR(10)	NOT NULL,
BlockTime		VARCHAR(10)	NOT NULL,
PRIMARY KEY (BlockCode)
);

CREATE TABLE STATUS_amk (
ApptStatusCode	CHAR(2),
ApptStatusDesc	VARCHAR(20)	NOT NULL,
PRIMARY KEY (ApptStatusCode)
);

CREATE TABLE REASON_amk (
ApptReasonCode	VARCHAR(3),
ApptReasonDesc	VARCHAR(30)	NOT NULL,
PRIMARY KEY (ApptReasonCode)
);

CREATE TABLE APPOINTMENT_amk (
ApptID		NUMBER(3,0),
ApptDate		DATE		NOT NULL,
ApptTime		VARCHAR(10)	NOT NULL,
PatientID		NUMBER(3,0)	NOT NULL,
DoctorID		NUMBER(1,0)	NOT NULL,
BillingType	VARCHAR(2)	NOT NULL,
InsCoID		NUMBER(3,0),
ApptStatusCode	CHAR(2)		NOT NULL,
PRIMARY KEY (ApptID),
FOREIGN KEY (InsCoID) REFERENCES INSCO_amk,
FOREIGN KEY (BillingType) REFERENCES BILLINGTYPE_amk,
FOREIGN KEY (DoctorID) REFERENCES DOCTOR_amk,
FOREIGN KEY (PatientID) REFERENCES PATIENT_amk,
FOREIGN KEY (ApptStatusCode) REFERENCES STATUS_amk
);

CREATE TABLE APPTDETAIL_amk (
ApptID		NUMBER(3,0),
ApptReasonCode	VARCHAR(3),
BlockCode	CHAR(2)		NOT NULL,
PRIMARY KEY (ApptID, ApptReasonCode),
FOREIGN KEY (BlockCode) REFERENCES BLOCK_amk
);

--Part Ib. Describe Tables

DESCRIBE INSCO_amk
DESCRIBE BILLINGTYPE_amk
DESCRIBE DOCTOR_amk
DESCRIBE PATIENT_amk
DESCRIBE BLOCK_amk
DESCRIBE STATUS_amk
DESCRIBE REASON_amk
DESCRIBE APPOINTMENT_amk
DESCRIBE APPTDETAIL_amk

--Part II. Insert Data

INSERT ALL
	INTO INSCO_amk VALUES (323,'Humana')
	INTO INSCO_amk VALUES (129,'Blue Cross')
	INTO INSCO_amk VALUES (210,'State Farm')
	INTO INSCO_amk VALUES (135,'TriCare')
	INTO BILLINGTYPE_amk VALUES ('I','Insurance')
	INTO BILLINGTYPE_amk VALUES ('SP','Self Pay')
	INTO BILLINGTYPE_amk VALUES ('WC','Worker''s Comp')
	INTO DOCTOR_amk VALUES (2,'Michael','Smith')
	INTO DOCTOR_amk VALUES (5,'Janice','May')
	INTO DOCTOR_amk VALUES (3,'Ray','Schultz')
	INTO PATIENT_amk VALUES (101,'Wesley','Tanner','8175551193')
	INTO PATIENT_amk VALUES (100,'Breanna','Rhodes','2145559191')
	INTO PATIENT_amk VALUES (15,'Jeff','Miner','4695552301')
	INTO PATIENT_amk VALUES (77,'Kim','Jackson','8175554911')
	INTO PATIENT_amk VALUES (119,'Mary','Vaughn','8175552334')
	INTO PATIENT_amk VALUES (97,'Chris','Mancha','4695553340')
	INTO PATIENT_amk VALUES (28,'Renee','Walker','2145559285')
	INTO PATIENT_amk VALUES (105,'Johnny','Redmond','2145551084')
	INTO PATIENT_amk VALUES (84,'James','Clayton','2145559285')
	INTO PATIENT_amk VALUES (23,'Shelby','Day','8175551198')
	INTO BLOCK_amk VALUES ('L1','Level 1','10 Minutes')
	INTO BLOCK_amk VALUES ('L2','Level 2','15 Minutes')
	INTO BLOCK_amk VALUES ('L3','Level 3','20 Minutes')
	INTO BLOCK_amk VALUES ('L4','Level 4','30 Minutes')
	INTO STATUS_amk VALUES ('CM','Complete')
	INTO STATUS_amk VALUES ('CN','Confirmed')
	INTO STATUS_amk VALUES ('NC','Not Confirmed')
	INTO REASON_amk VALUES ('NP','New Patient')
	INTO REASON_amk VALUES ('GBP','General Back Pain')
	INTO REASON_amk VALUES ('PSF','Post-Surgery Follow Up')
	INTO REASON_amk VALUES ('SR','Suture Removal')
	INTO REASON_amk VALUES ('PT','Physical Therapy')
	INTO REASON_amk VALUES ('AI','Auto Injury')
	INTO APPOINTMENT_amk VALUES (101,'01-SEP-2018','9:00 AM',101,2,'I',323,'CM')
	INTO APPOINTMENT_amk VALUES (102,'01-SEP-2018','9:00 AM',100,5,'I',129,'CM')
	INTO APPOINTMENT_amk VALUES (103,'01-SEP-2018','9:30 AM',15,2,'SP',NULL,'CM')
	INTO APPOINTMENT_amk VALUES (104,'01-SEP-2018','9:40 AM',77,3,'WC',210,'CM')
	INTO APPOINTMENT_amk VALUES (105,'01-SEP-2018','9:45 AM',119,2,'I',129,'CM')
	INTO APPOINTMENT_amk VALUES (106,'01-SEP-2018','10:00 AM',97,3,'SP',NULL,'CN')
	INTO APPOINTMENT_amk VALUES (107,'01-SEP-2018','10:30 AM',28,3,'I',129,'CN')
	INTO APPOINTMENT_amk VALUES (108,'01-SEP-2018','10:30 AM',105,2,'I',323,'NC')
	INTO APPOINTMENT_amk VALUES (109,'01-SEP-2018','11:00 AM',84,5,'I',135,'CN')
	INTO APPOINTMENT_amk VALUES (110,'01-SEP-2018','11:15 AM',84,3,'I',135,'CN')
	INTO APPOINTMENT_amk VALUES (111,'01-SEP-2018','1:00 PM',23,3,'I',323,'NC')
	INTO APPTDETAIL_amk VALUES  (101,'NP','L1')
	INTO APPTDETAIL_amk VALUES  (101,'GBP','L2')
	INTO APPTDETAIL_amk VALUES  (102,'PSF','L1')
	INTO APPTDETAIL_amk VALUES  (102,'SR','L1')
	INTO APPTDETAIL_amk VALUES  (103,'PSF','L1')
	INTO APPTDETAIL_amk VALUES  (104,'PT','L3')
	INTO APPTDETAIL_amk VALUES  (105,'NP','L1')
	INTO APPTDETAIL_amk VALUES  (105,'AI','L2')
	INTO APPTDETAIL_amk VALUES  (106,'PT','L4')
	INTO APPTDETAIL_amk VALUES  (107,'PT','L3')
	INTO APPTDETAIL_amk VALUES  (108,'GBP','L2')
	INTO APPTDETAIL_amk VALUES  (109,'PSF','L1')
	INTO APPTDETAIL_amk VALUES  (110,'PT','L4')
	INTO APPTDETAIL_amk VALUES  (111,'PT','L4')
SELECT * FROM dual;

COMMIT;

--PART IIb. Retrieve Data

SELECT * FROM INSCO_amk;
SELECT * FROM BILLINGTYPE_amk;
SELECT * FROM DOCTOR_amk;
SELECT * FROM PATIENT_amk;
SELECT * FROM BLOCK_amk;
SELECT * FROM STATUS_amk;
SELECT * FROM REASON_amk;
SELECT * FROM APPOINTMENT_amk;
SELECT * FROM APPTDETAIL_amk;

--PART III. Make changes

UPDATE PATIENT_amk
	SET PatientPhone = '2145551234'
	WHERE PatientID = 15;

INSERT INTO PATIENT_amk
	VALUES (120,'Amanda','Green',NULL);

INSERT INTO BLOCK_amk
	VALUES ('L5','Level 5','45 minutes');

INSERT INTO REASON_amk
	VALUES ('CSW','Complete Spinal Workup');

INSERT INTO INSCO_amk
	VALUES (324,'Cigna');

UPDATE APPOINTMENT_amk
	SET ApptDate = '02-SEP-2018'
	WHERE ApptID = 109 OR ApptID = 110 OR ApptID = 111;

INSERT INTO APPOINTMENT_amk
VALUES (112,'03-SEP-2018','10:30 AM',120,2,'WC',324,'NC');

INSERT ALL
	INTO APPTDETAIL_amk VALUES (112,'NP','L1')
	INTO APPTDETAIL_amk VALUES (112,'CSW','L5')
SELECT * FROM dual;

COMMIT;

--PART IV. Sorted Select

SELECT * FROM INSCO_amk
	ORDER BY InsCoID;
SELECT * FROM BILLINGTYPE_amk
	ORDER BY BillingType;
SELECT * FROM DOCTOR_amk
	ORDER BY DoctorID;
SELECT * FROM PATIENT_amk
	ORDER BY PatientID;
SELECT * FROM BLOCK_amk
	ORDER BY BlockCode;
SELECT * FROM STATUS_amk
	ORDER BY ApptStatusCode;
SELECT * FROM REASON_amk
	ORDER BY ApptReasonCode;
SELECT * FROM APPOINTMENT_amk
	ORDER BY ApptID;
SELECT * FROM APPTDETAIL_amk
	ORDER BY ApptID, ApptReasonCode;

spool off

set echo off

